-- CreateTable
CREATE TABLE "BusinessSettings" (
    "id" TEXT NOT NULL DEFAULT 'default',
    "name" TEXT NOT NULL DEFAULT 'One Burger',
    "tagline" TEXT,
    "description" TEXT,
    "logoUrl" TEXT,
    "logoMarkUrl" TEXT,
    "faviconUrl" TEXT,
    "ogImageUrl" TEXT,
    "primaryColor" TEXT NOT NULL DEFAULT '#2b6c96',
    "accentColor" TEXT NOT NULL DEFAULT '#eaf1f6',
    "backgroundColor" TEXT NOT NULL DEFAULT '#fbf9f5',
    "foregroundColor" TEXT NOT NULL DEFAULT '#23303a',
    "surfaceColor" TEXT NOT NULL DEFAULT '#ffffff',
    "headingFont" TEXT NOT NULL DEFAULT 'fraunces',
    "bodyFont" TEXT NOT NULL DEFAULT 'inter',
    "phone" TEXT,
    "whatsapp" TEXT,
    "email" TEXT,
    "instagram" TEXT,
    "facebook" TEXT,
    "tiktok" TEXT,
    "addressLine" TEXT,
    "city" TEXT,
    "addressReference" TEXT,
    "mapsUrl" TEXT,
    "latitude" DOUBLE PRECISION,
    "longitude" DOUBLE PRECISION,
    "timezone" TEXT NOT NULL DEFAULT 'America/Managua',
    "businessHours" JSONB NOT NULL,
    "currencyCode" TEXT NOT NULL DEFAULT 'NIO',
    "currencySymbol" TEXT NOT NULL DEFAULT 'C$',
    "locale" TEXT NOT NULL DEFAULT 'es-NI',
    "pickupLeadMinutes" INTEGER NOT NULL DEFAULT 25,
    "paymentInstructions" TEXT DEFAULT 'Pagás en el local al retirar tu pedido. No se cobra nada online.',
    "tipEnabled" BOOLEAN NOT NULL DEFAULT true,
    "tipRate" INTEGER NOT NULL DEFAULT 10,
    "isAcceptingOrders" BOOLEAN NOT NULL DEFAULT true,
    "closedMessage" TEXT DEFAULT 'Estamos cerrados. Podés mirar el menú y volver cuando abramos.',
    "updatedAt" TIMESTAMP(3) NOT NULL,
    "updatedByUserId" TEXT,

    CONSTRAINT "BusinessSettings_pkey" PRIMARY KEY ("id")
);

-- Seed de la fila única con los valores que hoy están escritos a mano en el
-- sitio público: el deploy de esta tarea no debe cambiar nada visible.
-- Idempotente por si la migración se aplica sobre una base que ya tenía la fila.
INSERT INTO "BusinessSettings" (
    "id",
    "name",
    "tagline",
    "description",
    "logoMarkUrl",
    "primaryColor",
    "accentColor",
    "backgroundColor",
    "foregroundColor",
    "surfaceColor",
    "headingFont",
    "bodyFont",
    "phone",
    "whatsapp",
    "instagram",
    "addressLine",
    "city",
    "timezone",
    "businessHours",
    "currencyCode",
    "currencySymbol",
    "locale",
    "pickupLeadMinutes",
    "paymentInstructions",
    "tipEnabled",
    "tipRate",
    "isAcceptingOrders",
    "closedMessage",
    "updatedAt"
) VALUES (
    'default',
    'One Burger',
    'Burgers preparadas al momento para llevar.',
    'Menu and pickup ordering platform for One Burger.',
    '/brand/one-burger-mark.svg',
    '#2b6c96',
    '#eaf1f6',
    '#fbf9f5',
    '#23303a',
    '#ffffff',
    'fraunces',
    'inter',
    '+50588770888',
    '50588770888',
    'oneburger',
    'Retiro en restaurante',
    'Jinotepe',
    'America/Managua',
    '{"mon":{"closed":false,"open":"12:00","close":"22:00"},"tue":{"closed":false,"open":"12:00","close":"22:00"},"wed":{"closed":false,"open":"12:00","close":"22:00"},"thu":{"closed":false,"open":"12:00","close":"22:00"},"fri":{"closed":false,"open":"12:00","close":"22:00"},"sat":{"closed":false,"open":"12:00","close":"22:00"},"sun":{"closed":false,"open":"12:00","close":"22:00"}}'::jsonb,
    'NIO',
    'C$',
    'es-NI',
    25,
    'Pagás en el local al retirar tu pedido. No se cobra nada online.',
    true,
    10,
    true,
    'Estamos cerrados. Podés mirar el menú y volver cuando abramos.',
    NOW()
) ON CONFLICT ("id") DO NOTHING;
